### ISSUE TITLE
Feature: bookmark questions | Task: back-end

### ISSUE THREAD

**Issue by ayla72** [CMU-313/spring23-nodebb-team-up#8]
Implement functionality that allows user to mark question as bookmarked while viewing a list of topics. Default state for question should be unmarked, when function is called, the question status should toggle from unbookmarked to bookmarked.

Estimated effort: 20+hrs

Dependencies: none

Acceptance criteria:
  - All questions are by default not bookmarked when initially posted.
  - Questions can be marked as bookmarked by instructor or student.
  - New database link to all bookmarked questions.
  - Automated test pass (correct output of adding and removing bookmarked posts)

**Comment by amitag2** [comment]
I was unable to complete this during Sprint 1 because it took longer than expected to understand the code structure of NodeBB and understand how to implement changes to the middleware. Additionally, my progress was impeded by issues with `npm run test` that were resolved towards the end of the sprint by shifting to working in a GitHub codespace.

**Comment by amitag2** [comment]
In response to TA feedback, we rescoped the bookmark feature to focus on displaying bookmarked post and did not continue to work on implementing this back end functionality for Sprint 2
